# Generated by Django 3.1.4 on 2020-12-24 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appstore', '0003_auto_20201224_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='marked_price',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name='product',
            name='selling_price',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
